### ISSUE TITLE
Knomi v2 Wi-Fi

### ISSUE THREAD

**Issue by 3dbrooks** [bigtreetech/KNOMI#38] opened 2023-11-12 23:28 UTC
Confirmed, Wi-Fi password is not retained after power is removed

**Comment by 3dbrooks** [comment] 2023-11-12 23:29
Knomi V2...

**Comment by 3dbrooks** [comment] 2023-11-15 17:41
I believe it briefly shows the logo and then back to the hello page with antenna connected . When I reconnect to it, the klipper IP is still in there but I must select my network from the list and recenter password. This did not happen at all with the original knomi

**Comment by oMTEo** [comment] 2023-11-19 07:36
I can also confirm this bug to my Knomi V1. After poweroff and on it 1st shows the Logo+circle then back to Hello-Page.

**Comment by irgendwer92** [comment] 2023-11-23 15:23
Same here on my Knomi V1

**Comment by Foose83** [comment] 2023-11-23 15:54
Same here on my Knomi V2

**Comment by Foose83** [comment] 2023-11-29 12:07
Hello. I entered a shorter ssid and it works correctly now.

**Comment by oMTEo** [comment] 2023-11-29 19:10
Ive tested now some WLAN-configurations with the presence of a team-member of BTT at discord and my results are : Passwords longer than 14 chars wouldnt keep hold after a powercycle of the Knomi. My SSID was only 3 chars at all tests.

I think (and hope) there will come an firmwareupdate soon :)

**Comment by 3dbrooks** [comment] 2023-11-29 20:26
This is very exciting, will test with a shorter password. Thanks

**Comment by MKloberg** [comment] 2023-12-01 00:54
@oMTEo Wow, very cool find! My SSID is 19 characters long and the password 15 characters.
I can't change any of that without affecting 33 other devices on my network, so I also hope that this will be fixed soon now that we know what the problem is.

**Comment by 3dbrooks** [comment] 2023-12-01 16:00
I changed my Wi-Fi password to 14 characters and my ssid is 6 characters and the issue remained. A second V2 behaves exactly the same. I have exhausted what I can do at my end. 
  I even removed the antenna, Wi-Fi password and put knomi next to my router so it was the only network it saw and even that did not resolve issue.

**Comment by oMTEo** [comment] 2023-12-01 16:12
Damn that thing suckz really, I was sure we´ve found the Bug.

**Comment by 3dbrooks** [comment] 2023-12-05 13:38
BTT sent me new firmware and it works!

**Comment by emintjeee** [comment] 2023-12-05 14:49
BTT sent me new firmware and it works!

**Comment by bigtreetech** [comment] 2023-12-06 02:35
Hi. The latest version of firmware should solve the bug of not saving WiFi when password or name are long.
KNOMI2:
https://github.com/bigtreetech/KNOMI/blob/master/KNOMI2/Firmware/knomi2_firmware.bin
KNOMI1:
https://github.com/bigtreetech/KNOMI/blob/master/KNOMI1/Firmware/knomi1_firmware.bin
Follow the steps below to update:
https://github.com/bigtreetech/KNOMI/#firmware-update

**Closed by bigtreetech** 2023-12-06 02:35 UTC

**Comment by Guilouz** [comment] 2023-12-08 22:43
@bigtreetech No change, same issue on KNOMI1

**Comment by Bazeone** [comment] 2024-01-03 03:45
same here.

**Comment by milo1987** [comment] 2025-03-16 17:41
same problems here! Wifi with 8 letters works, 14 not.
